logging:
  level:
    com:
      van0ss: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

server:
  port: 8080
  tomcat:
    accesslog:
      buffered: false
      directory: /dev
      enabled: true
      file-date-format: ''
      prefix: stdout
      suffix: ''

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

info:
  app:
    name: '@project.name@'
    version: '@project.version@'
